export const CART_ACTION_TYPES = {
    SET_CART_ITEMS: 'CART/SET_CART_ITEMS',
    SET_IS_CART_OPEN: 'CART/SET_IS_CART_OPEN',
    SET_CART_COUNT: 'CART/SET_CART_COUNT',
    SET_CART_TOTAL: 'CART/SET_CART_TOTAL',
}
